import type { NextPage } from "next";
import Head from "next/head";
import { Main } from "../components/sections/Main";
import { Skills } from "../components/sections/Skills";
import { Works } from "../components/sections/Works";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anibal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <Works />
      <Skills />
    </div>
  );
};

export default Home;
